/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.painkillergis.kc_gis_utils

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe

class AppTest : FunSpec({
  test("app has a greeting") {
    val classUnderTest = App()
    classUnderTest.greeting shouldBe "Hello World!"
  }
})
